PR for old Attribute Stuff
Aztlon/JedCore pull request #2
Opened 2020-12-11 23:21 UTC by StrangeOne101

I'm aware it can't be merged but I also cant see the issue so I'm PRing it in hope I can see the problem after

2020-12-11 23:22 UTC, StrangeOne101 commented
I love GitHub. I can fix the issues online

2020-12-16 13:34 UTC, Aztlon requested changes
Slight change requested in FrostBreath, looks good otherwise

2020-12-16 13:34 UTC, Aztlon commented on src/com/jedk1/jedcore/ability/waterbending/FrostBreath.java
>  			Biome.WOODED_BADLANDS_PLATEAU,
Could you delete this so there aren't two of the same biome in this list?

2020-12-17 00:06 UTC, StrangeOne101 commented
No idea how that got in there. Either way, removed

2020-12-17 01:21 UTC, Aztlon approved these changes

2020-12-17 01:47 UTC, merged